metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']
#  username: elastic
#  password: 
 
setup.dashboards.enabled: true
setup.kibana:
  host: "kibana:5601"

metricbeat.modules:

- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - core
    - diskio
    - socket
  enabled: true
  processes: ['.*']
  process.include_top_n:
    enabled: true
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory
  process.cmdline.cache.enabled: true
  process.cgroups.enabled: true

- module: system
  period: 10s
  metricsets:
    - filesystem
    - fsstat
#  processors:
#  - drop_event.when.regexp:
#      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
      
- module: system
  period: 15m
  metricsets:
    - uptime

#- module: system
#  period: 5m
#  metricsets:
#    - raid


